version: "3.9"
services:
  spy:
    image: gizmotronic/spyserver
    devices:
      - /dev/bus/usb/001/004
    environment:
      - LIST_IN_DIRECTORY=0
      - DEVICE_TYPE=RTL-SDR
      - BIND_PORT=5555
      - RTL_SN=1231
    ports:
      - "5555:5555"
    restart: unless-stopped
  adsb:
    image: sdr-adsb
    devices: 
      - /dev/bus/usb/001/005
    ports:
      - "1230:1230"
    environment:
      - MODE=publish
      - DEVICE_SN=1230
      - MQ_URL=mqtt://mq/adsb/raw
    entrypoint: "/entrypoint.sh"
    restart: unless-stopped
    depends_on:
      - mq
    networks: 
      - app-net
  mq:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./src/ctx/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: unless-stopped
    networks:
      - app-net
  db:
    image: mongo:4.2.23
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_store:/data/db
    restart: unless-stopped
    networks:
      - app-net
      - admin-net
  db-admin:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
    depends_on:
      - db
    networks:
      - admin-net
   app:
    image: nodered/node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "./data/app:/data"
    depends_on:
      - mq
      - db
    networks:
      - app-net
volumes:
  db_store:
networks:
  app-net:
  admin-net:
