version: "3.9"
services:
  spy:
    image: gizmotronic/spyserver
    devices:
      - /dev/bus/usb/001/004
    environment:
      - LIST_IN_DIRECTORY=0
      - DEVICE_TYPE=RTL-SDR
      - BIND_PORT=5555
      - RTL_SN=1231
    ports:
      - "5555:5555"
    restart: unless-stopped
    networks:
      - spynet
  adsb:
    image: sdr-adsb
    devices: 
      - /dev/bus/usb/001/005
    ports:
      - "1230:1230"
    environment:
      - MODE=publish
      - DEVICE_SN=1230
      - MQ_URL=mqtt://mq/adsb/raw
    entrypoint: "/entrypoint.sh"
    restart: unless-stopped
    depends_on:
      - mq
    networks: 
      - srcnet
  mq:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./src/ctx/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: unless-stopped
    networks:
      - srcnet
networks:
  spynet:
  srcnet:
